services:
  mqtt-broker:
    image: eclipse-mosquitto:2.0
    container_name: mqtt-broker
    hostname: mqtt
    networks:
      - edge-net
      - shared-net
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256m

  observer:
    build:
      context: .
      dockerfile: o11y/Dockerfile
    container_name: observer
    volumes:
      - ./o11y/:/app
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - mqtt-broker
    networks:
      - edge-net
      - shared-net
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256m
    command: ["python", "app.py"]

  datagen:
    container_name: datagen
    networks:
      - edge-net
    build:
      context: .
      dockerfile: ./datagen/Dockerfile
    volumes:
      - ./datagen:/app/datagen
      - ./common:/app/common
    depends_on:
      - mqtt-broker
    environment:
      - MQTT_BROKER=mqtt-
    command: ["tail", "-f", "/dev/null"]

  processing:
    container_name: processing
    networks:
      - edge-net
      - shared-net
    build:
      context: .
      dockerfile: ./processing/Dockerfile
    volumes:
      - ./processing:/app/processing
      - ./common:/app/common
    depends_on:
      - mqtt-broker
    environment:
      - MQTT_BROKER=mqtt-broker
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256m
    command: ["tail", "-f", "/dev/null"]

  influxdb:
    image: influxdb:2.7  # Versão estável
    container_name: influxdb
    hostname: influx
    ports:
      - "8086:8086"  # Porta padrão (mude se quiser 8181)
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=yourpassword
      - DOCKER_INFLUXDB_INIT_ORG=yourorg
      - DOCKER_INFLUXDB_INIT_BUCKET=sensor_data
    networks:
      - edge-net
      - shared-net
    volumes:
      - influxdb_data:/var/lib/influxdb2

  telegraf:
    image: telegraf:1.30
    container_name: telegraf
    hostname: telegraf
    restart: unless-stopped
    environment:
      - INFLUX_TOKEN=${INFLUX_TOKEN}
    volumes:
      - ./config/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    networks:
      - edge-net
      - shared-net

networks:
  edge-net:
    driver: bridge
  cloud-net:
    driver: bridge
  shared-net:
    external: true

volumes:
  influxdb_data:
