x-common-resources: &common-resources
  deploy:
    resources:
      limits:
        cpus: '0.25'
        memory: 256m

x-common-networks: &common-networks
  networks:
    - edge-net
    - shared-net

services:
  mqtt-broker:
    image: eclipse-mosquitto:2.0
    container_name: mqtt-broker
    hostname: mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    <<: [*common-networks, *common-resources]

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    hostname: influx
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=yourpassword
      - DOCKER_INFLUXDB_INIT_ORG=yourorg
      - DOCKER_INFLUXDB_INIT_BUCKET=sensor_data
    <<: *common-networks
    volumes:
      - influxdb_data:/var/lib/influxdb2

  telegraf:
    image: telegraf:1.30
    container_name: telegraf
    hostname: telegraf
    restart: unless-stopped
    group_add:
      - 1001 # docker group
    environment:
      - INFLUX_TOKEN=${INFLUX_TOKEN}
    volumes:
      - ./config/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - influxdb
    <<: *common-networks

  metrics-db:
    image: postgres:16-alpine
    container_name: metrics-db
    hostname: metrics_db
    environment:
      POSTGRES_USER: user_tcc
      POSTGRES_PASSWORD: password_tcc
      POSTGRES_DB: metrics
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user_tcc -d metrics" ]
      interval: 10s
      timeout: 5s
      retries: 5
    <<: *common-networks

  datagen:
    container_name: datagen
    networks:
      - edge-net
    build:
      context: .
      dockerfile: datagen/Dockerfile
    volumes:
      - ./datagen:/app/datagen
      - ./common:/app/common
    depends_on:
      - mqtt-broker
    environment:
      - MQTT_BROKER=mqtt-broker
    command: ["python", "datagen/app.py"]

  processing:
    container_name: processing
    build:
      context: .
      dockerfile: processing/Dockerfile
    volumes:
      - ./processing:/app/processing
      - ./common:/app/common
    depends_on:
      - mqtt-broker
    environment:
      - MQTT_BROKER=mqtt-broker
    <<: [*common-networks, *common-resources]
    command: ["tail", "-f", "/dev/null"]

  simulation:
    build:
      context: .
      dockerfile: simulation/Dockerfile
    container_name: simulation
    depends_on:
      metrics-db:
        condition: service_healthy
    env_file: .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./simulation:/app/simulation
    <<: *common-networks
    command: ["python", "simulation/app.py"]

networks:
  edge-net:
    driver: bridge
  shared-net:
    external: true

volumes:
  influxdb_data:
