[agent]
  ## Intervalo de coleta. 1 segundo é ideal para capturar picos.
  interval = "2s"
  flush_interval = "5s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_jitter = "0s"
  precision = ""
  hostname = ""
  omit_hostname = false

[[outputs.influxdb_v2]]
  # Colchetes são necessários para 'urls' (é um array)
  urls = ["${INFLUX_URL}"]
  token = "${INFLUX_TOKEN}"
  organization = "${INFLUX_ORG}"
  bucket = "${INFLUX_BUCKET}"

[[inputs.mqtt_consumer]]
  servers = ["ssl://1f7a01b9544f4063bb9409d0b91ac77c.s1.eu.hivemq.cloud:8883"]
  username = "${MQTT_USERNAME}"
  password = "${MQTT_PASSWORD}"

  # Tópico específico para este bloco
  topics = [
    "sensors/aggregations"
  ]

  data_format = "json"

  # Define a "tabela" (measurement) no InfluxDB
  name_override = "aggregations"

  # Define quais campos do JSON serão "Tags" (para filtrar)
  tag_keys = ["sensor_id"]

  # (Telegraf irá inferir automaticamente os campos numéricos
  # como avg_rpm, max_temperature, etc.)

# ==========================================================
# ENTRADA 2: APENAS ALERTAS
# ==========================================================
[[inputs.mqtt_consumer]]
  servers = ["ssl://1f7a01b9544f4063bb9409d0b91ac77c.s1.eu.hivemq.cloud:8883"]
  username = "${MQTT_USERNAME}"
  password = "${MQTT_PASSWORD}"

  # Tópico específico para este bloco
  topics = [
    "sensors/alerts"
  ]

  data_format = "json"

  # Define uma "tabela" (measurement) SEPARADA para os alertas
  name_override = "alerts"

  # Define quais campos do JSON serão "Tags"
  tag_keys = [
    "sensor_id",
    "type",
    "severity"
  ]

  # Define quais campos devem ser SEMPRE tratados como texto (string)
  json_string_fields = [
    "event_id",
    "details",
    "timestamp" # (O timestamp do evento original, não o do Telegraf)
  ]

