[agent]
  ## Intervalo de coleta. 1 segundo é ideal para capturar picos.
  interval = "2s"
  flush_interval = "5s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_jitter = "0s"
  precision = ""
  hostname = ""
  omit_hostname = false

[[outputs.influxdb_v2]]
  urls = ["http://influx:8086"]
  token = "${INFLUX_TOKEN}"
  organization = "yourorg"
  bucket = "sensor_data"

[[inputs.mqtt_consumer]]
  servers = ["tcp://mqtt-broker:1883"]
  topics = [
    "telegraf/host01/cpu",
    "telegraf/+/mem",
    "sensors/#",
  ]

  data_format = "json"

[[inputs.docker]]
  endpoint = "unix:///var/run/docker.sock"
  data_format = "json"